extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/prof_plewis
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/r/proflewis/geog0111
  - icon: fontawesome/brands/github
    link: https://github.com/UCL-EO/geog0111
google_analytics:
- UA-1347772-1
- auto
markdown_extensions:
- meta
nav: []
plugins:
- git-revision-date-localized
- exclude:
    glob:
    - __pycache__
    - '*.bin'
    - '*.hdf'
    - '*.nc'
    - '*.zip'
    - '*.npz'
- search
- mkdocs-jupyter:
    include_source: true
repo_url: https://github.com/UCL-EO/geog0111
site_author: Prof P. Lewis
site_name: GEOG0111
site_url: http://www2.geog.ucl.ac.uk/~plewis/geog0111
theme:
  favicon: images/ucl_logo.png
  features:
  - search.highlight
  - header.hide
  name: material
