extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/prof_plewis
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/r/proflewis/geog0111
  - icon: fontawesome/brands/github
    link: https://github.com/UCL-EO/geog0111
nav:
- Introduction: index.md
- Course Basics:
  - Part1: 000_Part1.md
  - Notebook Use: 001_Notebook_use.md
  - Unix: 002_Unix.md
  - Help: 003_Help.md
  - Accounts: 004_Accounts.md
  - Packages: 005_Packages.md
  - Answers:
    - Notebook Use: 001_Notebook_use_answers.md
    - Unix: 002_Unix_answers.md
    - Help: 003_Help_answers.md
- Core Concepts:
  - Part2: 010_Part2.md
  - Python Introduction: 010_Python_Introduction.md
  - Python Data Types: 011_Python_data_types.md
  - Python Strings: 012_Python_strings.md
  - Python String Methods: 013_Python_string_methods.md
  - Python Groups: 014_Python_groups.md
  - Python Control: 015_Python_control.md
  - Python For: 016_Python_for.md
  - Functions: 017_Functions.md
  - Running Python: 018_Running_Python.md
  - Answers:
    - Python Introduction: 010_Python_Introduction_answers.md
    - Python Data Types: 011_Python_data_types_answers.md
    - Python Strings: 012_Python_strings_answers.md
    - Python String Methods: 013_Python_string_methods_answers.md
    - Python Groups: 014_Python_groups_answers.md
    - Python Control: 015_Python_control_answers.md
    - Python For: 016_Python_for_answers.md
    - Functions: 017_Functions_answers.md
    - Running Python: 018_Running_Python_answers.md
- Datasets:
  - Part3: 020_Part3.md
  - Python Files: 021_Python_files.md
  - Read Files: 022_Read_files.md
  - Pandas And Plotting: 023_Pandas_and_plotting.md
  - NASA MODIS Earthdata: 024_NASA_MODIS_Earthdata.md
  - Google Earth Engine: 025_GoogleEarthEngine.md
  - Numpy Matplotlib: 026_Numpy_matplotlib.md
  - Answers:
    - Python Files: 021_Python_files_answers.md
    - Read Files: 022_Read_files_answers.md
    - NASA MODIS Earthdata: 024_NASA_MODIS_Earthdata_answers.md
- Geospatial Data:
  - Part4: 030_Part4.md
  - GDAL: 031_GDAL.md
  - MODIS Download: 032_MODIS_download.md
  - GDAL Stacking And Interpolating: 033_GDAL_stacking_and_interpolating.md
  - GDAL Reconciling Projections: 034_GDAL_Reconciling_projections.md
  - GDAL Masking: 034_GDAL_masking.md
- Modelling:
  - Linear Models: 041_Linear_models.md
  - Modelling And Optimisation: 042_Modelling_and_optimisation.md
- Developers:
  - Local Install: DEV_Local_Install.md
  - Scripts: DEV_scripts.md
plugins:
- git-revision-date-localized
- exclude:
    glob:
    - work/*
    - __pycache__
    - '*.bin'
    - '*.hdf'
    - '*.nc'
    - '*.zip'
    - '*.npz'
- search
- mkdocs-jupyter:
    include_source: true
repo_url: https://github.com/UCL-EO/geog0111
site_author: Prof P. Lewis
site_name: GEOG0111
site_url: https://ucl-eo.github.io/geog0111
theme:
  favicon: images/ucl.png
  name: material
