extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/prof_plewis
  - icon: fontawesome/brands/docker
    link: https://hub.docker.com/r/proflewis/geog0111
  - icon: fontawesome/brands/github
    link: https://github.com/UCL-EO/geog0111
nav:
- Introduction: index.md
- Course Basics:
  - Notebook Use: 001_Notebook_use.md
  - Unix: 002_Unix.md
  - Help: 003_Help.md
  - Accounts: 004_Accounts.md
  - Packages: 005_Packages.md
  - Answers:
    - Notebook Use: 001_Notebook_use_answers.md
    - Unix: 002_Unix_answers.md
    - Help: 003_Help_answers.md
- Core Concepts:
  - Python Introduction: 010_Python_Introduction.md
  - Python Data Types: 011_Python_data_types.md
  - Python Strings: 012_Python_strings.md
  - Python String Methods: 013_Python_string_methods.md
  - Python Groups: 014_Python_groups.md
  - Python Control: 015_Python_control.md
  - Python For: 016_Python_for.md
  - Functions: 017_Functions.md
  - Running Python: 018_Running_Python.md
  - Answers:
    - Python Introduction: 010_Python_Introduction_answers.md
    - Python Data Types: 011_Python_data_types_answers.md
    - Python Strings: 012_Python_strings_answers.md
    - Python String Methods: 013_Python_string_methods_answers.md
    - Python Groups: 014_Python_groups_answers.md
    - Python Control: 015_Python_control_answers.md
    - Python For: 016_Python_for_answers.md
    - Functions: 017_Functions_answers.md
    - Running Python: 018_Running_Python_answers.md
- Datasets:
  - Python Files: 020_Python_files.md
  - Streams: 021_Streams.md
  - Read Write Files: 022_Read_write_files.md
  - Plotting: 023_Plotting.md
  - Image Display: 024_Image_display.md
  - Answers:
    - Python Files: 020_Python_files_answers.md
    - Streams: 021_Streams_answers.md
    - Read Write Files: 022_Read_write_files_answers.md
    - Plotting: 023_Plotting_answers.md
    - Image Display: 024_Image_display_answers.md
- Geospatial Data:
  - NASA MODIS Earthdata: 030_NASA_MODIS_Earthdata.md
  - Numpy: 031_Numpy.md
  - GDAL Mosaicing And Masking: 032_GDAL_mosaicing_and_masking.md
  - GDAL Timeseries: 033_GDAL_timeseries.md
  - Weigthed Smoothing And Interpolation: 034_Weigthed_smoothing_and_interpolation.md
  - Weighted Interpolation: 035_Weighted_interpolation.md
  - Model Fitting: 036_Model_Fitting.md
  - Answers:
    - NASA MODIS Earthdata: 030_NASA_MODIS_Earthdata_answers.md
    - Numpy: 031_Numpy_answers.md
    - GDAL Mosaicing And Masking: 032_GDAL_mosaicing_and_masking_answers.md
- Modelling:
  - Practical Part1: 040_Practical_Part1.md
  - Practical Part2: 041_Practical_Part2.md
plugins:
- git-revision-date-localized
- exclude:
    glob:
    - work/*
    - __pycache__
    - '*.bin'
    - '*.hdf'
    - '*.nc'
    - '*.zip'
    - '*.npz'
- search
- mkdocs-jupyter:
    include_source: true
repo_url: https://github.com/UCL-EO/geog0111
site_author: Prof P. Lewis
site_name: GEOG0111
site_url: https://ucl-eo.github.io/geog0111
theme:
  favicon: images/ucl.png
  name: material
