name: geog0111
channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - python>=3.7
  - numpy
  - geemap
  - jupyter
  - nbgitpuller
  - mkdocs
  - pycodestyle
  - sphinx
  - pip:
    - mkdocs-jupyter
    - urlpath
    - jupyter_contrib_nbextensions
    - mknotebooks
    - mkdocs-material
    - mkdocs-exclude
    - mkdocs-git-revision-date-localized-plugin
